repos:
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: v2.0.4
#     hooks:
#     -   id: autopep8
# # -   repo: https://github.com/pycqa/flake8
# #     rev: v3.9.2
# #     hooks:
# #     -   id: flake8
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black



