runtime: python310

entrypoint: gunicorn -b :$PORT run:app 

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.10"

env_variables:
    FLASK_SECRET_KEY: "QTV4TeJZgLCSQbIGzHHKTnhTvaiDyRiH"
    LINKEDIN_ACCESS_TOKEN: "AQVWdI5zP-4RMdhewXjRK2D-pcpf0-NIDoh3yzGARaWkbSeyCjpqes1AQ8u4h3R5ZY3FZpJ0to8xi77FTT5MelsG72fEZSJwFq2_S_BQFInhR_mPbsVDeiMNboxMsDU2pmG00rF4eKRyXiy1yfLPXNNQuROtR20fi6Vdhcgk3grzS3VrP_czP-O_VB3QDMS5rjyFj-klg5j5BTjC-iLtGzfJOMKFsquWTvoJdYKlmX5FoLzReR4QlkhVFJM4GCBA4ofi7325H2KrA_IoTKPXIcKLyO9mbzKOLLaPApx_WeFkiHBbco0xk60k4TBZykc3cqp7te3P9SkS9JjZM_Or_Q5Yh4tCOw"
    LINKEDIN_CLIENT_ID: "77an2m260n9s7e"
    LINKEDIN_CLIENT_SECRET: "zR5hGMcR3w9jz48g"
    GOOGLE_CLIENT_ID: "368483444927-3bs3m87clllkr6t7rbe4mqdi54r0g1mt.apps.googleusercontent.com"
    GOOGLE_CLIENT_SECRET: "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"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto